# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20170302_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('SA', 'System Admin'), ('C', 'Customer'), ('R', 'Restaurant')], default='C', max_length=2),
        ),
    ]
